"""Bake each atlas outfit's SIGNATURE geometry (the eye-bubble helm, the
riveted patch-plates, the mechanic's tool belt, ...) into
game/world/figure_signatures.py, so Person.draw() can render it in game.

The signature functions in common_kit / vherathi_outfits / drossholt_outfits /
federation_outfits return (base_opts, pre_svg, post_svg). The base is a plain
recolour (already handled by graphics.json + figure_parts). This script parses
the pre/post SVG strings - only <polygon>/<circle>, which is all those
functions emit - into flat part lists, maps figure-space coords into Person
game units (same transform build_person_figure.py uses), and writes:

    SIGNATURE = {
        "<signature id>": {"pre": [...parts behind the body...],
                           "post": [...parts over the body...]},
        ...
    }

A part is {"points"|"circle", "color": "#rrggbb"[, "op": float]}. `Person.
_fig_color` resolves a "#..." colour literally. Re-run after editing an
outfit signature; graphics.json outfit entries opt in with a "signature" key.
"""
import importlib
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
sys.path.insert(0, str(HERE))
import gen_si

S = 0.19
GROUND = gen_si.FIG_FOOT_Y + 10.0


def g(x, y):
    return round((x - 70.0) * S, 3), round((y - GROUND) * S, 3)


_POLY = re.compile(r'<polygon\b[^>]*\bpoints="([^"]*)"[^>]*?(?:\bfill="([^"]*)")?[^>]*?(?:\bopacity="([^"]*)")?[^>]*/>')
_CIRC = re.compile(r'<circle\b[^>]*\bcx="([^"]*)"[^>]*\bcy="([^"]*)"[^>]*\br="([^"]*)"[^>]*?(?:\bfill="([^"]*)")?[^>]*?(?:\bopacity="([^"]*)")?[^>]*/>')
_TAG = re.compile(r'<(polygon|circle)\b[^>]*/>')
_ATTR = re.compile(r'\b([a-z-]+)="([^"]*)"')


def parse_shapes(svg):
    """Every <polygon>/<circle> in `svg`, in document order, as game-unit parts."""
    out = []
    for m in _TAG.finditer(svg or ""):
        attrs = dict(_ATTR.findall(m.group(0)))
        fill = attrs.get("fill", "#969696")
        if fill in ("url(#grid)", "none"):
            continue
        op = attrs.get("opacity")
        part = {"color": fill}
        if op is not None:
            part["op"] = round(float(op), 3)
        if m.group(1) == "polygon":
            pts = [tuple(float(v) for v in pair.split(",")) for pair in attrs["points"].split()]
            if len(pts) < 3:
                continue
            part["points"] = [list(g(px, py)) for px, py in pts]
        else:
            cx, cy, r = float(attrs["cx"]), float(attrs["cy"]), float(attrs["r"])
            gx, gy = g(cx, cy)
            part["circle"] = [gx, gy, round(r * S, 3)]
        out.append(part)
    return out


# module -> graphics.json-facing prefix for the signature id
MODULES = [("common_kit", ""), ("vherathi_outfits", "vherathi_"),
           ("drossholt_outfits", "drossholt_"), ("federation_outfits", "federation_")]


def build():
    sig = {}
    for modname, prefix in MODULES:
        mod = importlib.import_module(modname)
        for key, entry in mod.OUTFITS.items():
            fn = entry[0]
            _base, pre, post = fn()
            pre_p, post_p = parse_shapes(pre), parse_shapes(post)
            if not pre_p and not post_p:
                continue                       # e.g. plain space_suit - no signature
            sig[prefix + key] = {"pre": pre_p, "post": post_p}
    return sig


def d(v):
    return json.dumps(v, separators=(",", ":"))


if __name__ == "__main__":
    sig = build()
    lines = ['"""Generated by docs/atlases/build_figure_signatures.py.',
             'Per-outfit signature geometry (eye-bubble helm, patch-plates, tool belt, ...),',
             'in Person game units. Do not hand-edit; re-run the builder. See DESIGN_ATLAS.md."""',
             "", "SIGNATURE = {"]
    for k in sorted(sig):
        lines.append(f"    {json.dumps(k)}: {{")
        for slot in ("pre", "post"):
            lines.append(f'        {json.dumps(slot)}: [')
            for p in sig[k][slot]:
                lines.append(f"            {d(p)},")
            lines.append("        ],")
        lines.append("    },")
    lines.append("}")
    dest = pathlib.Path("game/world/figure_signatures.py")
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("wrote", dest, "-", len(sig), "signatures:")
    for k in sorted(sig):
        print(f"  {k:26} pre={len(sig[k]['pre']):2} post={len(sig[k]['post']):2}")
